# Generated by Django 3.2.16 on 2023-02-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=45)),
                ('capacity', models.IntegerField()),
                ('levels', models.IntegerField()),
            ],
            options={
                'db_table': 'HOUSE',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependences', to='core.person')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='core.house')),
                ('houses', models.ManyToManyField(related_name='owners', to='core.House')),
            ],
            options={
                'db_table': 'PERSON', 
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('governor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governed_town', to='core.person')),
            ],
            options={
                'db_table': 'TOWN',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.town'),
        ),
    ]
